apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langflow.fullname" . }}-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
      gzip on;
      gzip_comp_level  2;
      gzip_min_length  1000;
      gzip_types  text/xml text/css;
      gzip_http_version 1.1;
      gzip_vary  on;
      gzip_disable "MSIE [4-6] \.";

      listen 8080;

      location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          try_files $uri $uri/ /index.html =404;
      }
      location /api {
          proxy_pass http://langflow-backend.langflow.svc.cluster.local:7860;
      }
      location /health_check {
          proxy_pass http://langflow-backend.langflow.svc.cluster.local:7860;
      }
      location /health {
          proxy_pass http://langflow-backend.langflow.svc.cluster.local:7860;
      }

      include /etc/nginx/extra-conf.d/*.conf;
    }