# {{- if not (hasKey .Values.postgresql "existingSecret") }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: langflow-ide-postgresql-service  # Ensure this matches your StatefulSet reference
#   namespace: {{ .Release.Namespace }} 
# type: Opaque
# data:
#   POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc }}
#   POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
#   POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc }}
# {{- end }}