apiVersion: v1
kind: Service
metadata:
  name: {{ include "langflow-runtime.fullname" . }}-langflow
  labels:
    app: langflow
    {{- include "langflow-runtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.langflow.service.type }}
  ports:
    - port: {{ .Values.langflow.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: langflow