apiVersion: v1
kind: Service
metadata:
  name: {{ include "langflow-runtime.fullname" . }}-mysql
  labels:
    app: mysql
    {{- include "langflow-runtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: mysql