apiVersion: v1
kind: Service
metadata:
  name: {{ include "langflow-runtime.fullname" . }}-postgres
  labels:
    app: postgres
    {{- include "langflow-runtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: postgres